# Unofficial nifi image at: https://github.com/ijokarumawak/docker-compose-nifi-cluster/tree/7de29addcd050ef2f45c7ae73a82924f1f916ed4
version: '2'
services:
  zoo1:
    container_name: zookeeper
    image: zookeeper
    restart: always
    ports:
      - 2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zoo1:2888:3888

  nifi-seed:
    container_name: nifi-coordinator
    build: ./nifi-node
    image: nifi-node:1.0.0
    ports:
#      - "8080-8082:8080-8082"
      - "9090-9092:9090-9092"
    depends_on:
      - zoo1

  nifi-nodes:
    image: nifi-node:1.0.0
    depends_on:
      - nifi-seed
